Automatically load all interop assemblies before loading plugins
BepInEx/BepInEx pull request #777
Opened 2024-02-09 00:49 UTC by ManlyMarco

Assemblies are often loaded on the il2cpp side but not on the mono side, causing confusion when using reflection.
This will load all interop assemblies right before plugins are loaded, which should partially avoid these issues at a low time cost of around 40ms.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-06-13 19:06 UTC, js6pak requested changes

2024-06-13 19:06 UTC, js6pak commented on Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
> +                System.Threading.Interlocked.Increment(ref loaded);
```suggestion
                Interlocked.Increment(ref loaded);
```

2024-06-13 19:06 UTC, js6pak commented on Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
> +                Logger.Log(BepInEx.Logging.LogLevel.Warning, $"Failed to preload {file} - {e}");
```suggestion
                Logger.LogWarning($"Failed to preload {file} - {e}");
```

2024-06-13 19:06 UTC, js6pak commented on Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
> +        Logger.Log(BepInEx.Logging.LogLevel.Debug, $"Preloaded {loaded} interop assemblies in {sw.ElapsedMilliseconds}ms");
```suggestion
        Logger.LogDebug($"Preloaded {loaded} interop assemblies in {sw.ElapsedMilliseconds}ms");
```

2024-06-14 20:08 UTC, ManlyMarco commented on Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
> +        var files = Directory.EnumerateFiles(IL2CPPInteropAssemblyPath);
I did this on purpose to make filtering multithreaded, it gives a measurable speed increase.

2024-06-14 20:14 UTC, ManlyMarco commented on Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
> +            if (file.EndsWith("netstandard.dll", StringComparison.OrdinalIgnoreCase)) return;
Trying to load both netstandard.dll and Il2Cppnetstandard.dll causes issues. I didn't want to add an extra if check.

2024-06-14 20:16 UTC, ManlyMarco commented on Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
> +        System.Threading.Tasks.Parallel.ForEach(files, file =>
I didn't want to add two extra usings just for this.

2024-06-20 16:22 UTC, ManlyMarco commented
Is the PR good to merge now? The remaining conversations we talked about on discord, it runs faster the way it is now.

2024-09-05 17:12 UTC, ManlyMarco commented on Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs
> +            if (file.EndsWith("netstandard.dll", StringComparison.OrdinalIgnoreCase)) return;
```suggestion
            if (file.Equals("netstandard.dll", StringComparison.OrdinalIgnoreCase)) return;
            if (file.Equals("Il2Cppnetstandard.dll", StringComparison.OrdinalIgnoreCase)) return;
```

2024-09-08 13:31 UTC, bbepis approved these changes

2024-09-08 13:45 UTC, merged